#!/usr/bin/env node
// DTCG → dist/tokens.css + dist/tokens.json. Zero dependencies; throws on any rule break.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const NAME_GRAMMAR =
  /^--sk-[a-z][a-z0-9]*(?:-[a-z][a-z0-9]*){0,2}--[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const PHYSICAL_WORDS = new Set([
  'left',
  'right',
  'top',
  'bottom',
  'width',
  'height',
  'horizontal',
  'vertical',
]);
const THEME_MODES = ['dark'];
const MOTION_MODES = ['reduced'];

const isAlias = (v) => typeof v === 'string' && /^\{[^}]+\}$/.test(v);

function collect(tree, tier, out, path = [], inheritedType) {
  const type = tree.$type ?? inheritedType;
  if ('$value' in tree) {
    out.push({ path, tier, type, raw: tree.$value, modes: tree.$extensions?.['sk.modes'] ?? {} });
    return out;
  }
  // JS orders integer-like keys ("1000") before "0000"; restore scale order.
  const entries = Object.entries(tree).filter(([key]) => !key.startsWith('$'));
  if (entries.every(([key]) => /^\d+$/.test(key))) entries.sort(([a], [b]) => a.localeCompare(b));
  for (const [key, child] of entries) {
    collect(child, tier, out, [...path, key], type);
  }
  return out;
}

export function tokenName(path) {
  const id = path.join('.');
  if (path.length < 2) throw new Error(`${id}: needs at least category and modifier`);
  const name = `--sk-${path.slice(0, -1).join('-')}--${path.at(-1)}`;
  if (!NAME_GRAMMAR.test(name)) throw new Error(`${id}: "${name}" breaks the token grammar`);
  const physical = path.flatMap((s) => s.split('-')).find((w) => PHYSICAL_WORDS.has(w));
  if (physical) throw new Error(`${id}: physical direction "${physical}" in name`);
  return name;
}

export function formatValue(type, value, id) {
  switch (type) {
    case 'color':
    case 'fontWeight':
    case 'number':
      return String(value);
    case 'dimension':
    case 'duration':
      return typeof value === 'object' ? `${value.value}${value.unit}` : String(value);
    case 'fontFamily':
      return Array.isArray(value)
        ? value.map((f) => (/\s/.test(f) ? `'${f}'` : f)).join(', ')
        : String(value);
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`;
    default:
      throw new Error(`${id}: unsupported $type "${type}"`);
  }
}

export function buildTokens({ primitive, semantic }) {
  const tokens = [...collect(primitive, 'primitive', []), ...collect(semantic, 'semantic', [])];
  const byPath = new Map();
  const byName = new Map();

  for (const t of tokens) {
    t.id = t.path.join('.');
    t.name = tokenName(t.path);
    if (!t.type) throw new Error(`${t.id}: missing $type`);
    const clash = byName.get(t.name);
    if (clash) {
      throw new Error(`${t.id}: name ${t.name} already used by ${clash.tier} ${clash.id}`);
    }
    if (t.tier === 'primitive' && isAlias(t.raw)) {
      throw new Error(`${t.id}: primitives hold literal values, not aliases`);
    }
    byPath.set(t.id, t);
    byName.set(t.name, t);
  }

  // Resolve a raw value to { css, literal }; css keeps the var() chain, literal is the final value.
  const resolve = (t, raw, seen = []) => {
    if (!isAlias(raw)) {
      const literal = formatValue(t.type, raw, t.id);
      return { css: literal, literal };
    }
    const ref = raw.slice(1, -1);
    const target = byPath.get(ref);
    if (!target) throw new Error(`${t.id}: unresolved alias {${ref}}`);
    if (seen.includes(ref)) throw new Error(`${t.id}: alias cycle ${[...seen, ref].join(' → ')}`);
    if (target.type !== t.type) {
      throw new Error(`${t.id}: $type ${t.type} aliases ${ref} of $type ${target.type}`);
    }
    const { literal } = resolve(target, target.raw, [...seen, ref]);
    return { css: `var(${target.name}, ${literal})`, literal };
  };

  for (const t of tokens) {
    t.value = resolve(t, t.raw);
    t.modeValues = Object.fromEntries(
      Object.entries(t.modes).map(([mode, raw]) => {
        if (![...THEME_MODES, ...MOTION_MODES].includes(mode)) {
          throw new Error(`${t.id}: unknown mode "${mode}"`);
        }
        return [mode, resolve(t, raw)];
      }),
    );
  }

  const decl = (list, pick, indent) =>
    list.map((t) => `${indent}${t.name}: ${pick(t)};`).join('\n');
  const withMode = (mode) => tokens.filter((t) => t.modeValues[mode]);
  const dark = withMode('dark');
  const reduced = withMode('reduced');
  const durations = tokens.filter((t) => t.tier === 'semantic' && t.type === 'duration');

  const css = `/* Generated by @sklop/tokens. Do not edit. */
@layer sklop.tokens, sklop.components;

@layer sklop.tokens {
  :root {
    color-scheme: light dark;
${decl(tokens, (t) => t.value.css, '    ')}
  }

  [data-sk-theme='light'] {
    color-scheme: light;
${decl(dark, (t) => t.value.css, '    ')}
  }

  [data-sk-theme='dark'] {
    color-scheme: dark;
${decl(dark, (t) => t.modeValues.dark.css, '    ')}
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-sk-theme]) {
      color-scheme: dark;
${decl(dark, (t) => t.modeValues.dark.css, '      ')}
    }
  }

  /* Guard on presence, not value: any explicit data-sk-motion wins over the media query. */
  @media (prefers-reduced-motion: reduce) {
    :root:not([data-sk-motion]) {
${decl(reduced, (t) => t.modeValues.reduced.css, '      ')}
    }
  }

  [data-sk-motion='reduced'] {
${decl(reduced, (t) => t.modeValues.reduced.css, '    ')}
  }

  [data-sk-motion='off'] {
${decl(durations, () => '0ms', '    ')}
  }
}
`;

  const json = tokens.map((t) => ({
    name: t.name,
    path: t.id,
    tier: t.tier,
    type: t.type,
    value: t.value.literal,
    css: t.value.css,
    modes: Object.fromEntries(Object.entries(t.modeValues).map(([m, v]) => [m, v.literal])),
  }));

  return { css, json };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  const read = (f) => JSON.parse(readFileSync(join(root, 'src', f), 'utf8'));
  const { css, json } = buildTokens({
    primitive: read('primitive.tokens.json'),
    semantic: read('semantic.tokens.json'),
  });
  mkdirSync(join(root, 'dist'), { recursive: true });
  writeFileSync(join(root, 'dist', 'tokens.css'), css);
  writeFileSync(join(root, 'dist', 'tokens.json'), `${JSON.stringify(json, null, 2)}\n`);
  console.log(`@sklop/tokens: ${json.length} tokens`);
}
